#!/bin/bash



# install kubernetes
set -e
VERSION=${VERSION:-v1.3.0}
OS=${OS:-darwin}
ARCH=${ARCH:-amd64}
curl -Lo minikube https://storage.googleapis.com/minikube/releases/$VERSION/minikube-$OS-$ARCH \
  && chmod +x minikube \
&& sudo mv minikube /usr/local/bin/



# install docker
apt-get update
apt-get install -y apt-transport-https ca-certificates
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get purge lxc-docker
apt-cache policy docker-engine
apt-get update
apt-get upgrade -y
apt-get install -y linux-image-extra-$(uname -r)
apt-get install -y docker-engine
service docker start

apt-get install -y vim

mkdir /test