#!/bin/bash
# install kubernetes

apt-get upgrade
apt-get update
#bash kubernetes_install.sh
#curl https://storage.googleapis.com/kubernetes-release/release/v1.2.0/bin/darwin/amd64/kubectl > kubectl
#chmod 750 kubectl
#cat ~/.kube/config

#install salt master
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sh bootstrap-salt.sh -M -N git develop

apt-get install salt-master -y
echo "interface: 10.0.1.1" >> /etc/salt/master
systemctl restart salt-master
sed -i "1 a127.0.1.1 $HOSTNAME" /etc/hosts

#install docker
#apt-get update
#apt-get install -y apt-transport-https ca-certificates
#apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
#echo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' > /etc/apt/sources.list.d/docker.list
#apt-get update
#apt-get purge lxc-docker
#apt-cache policy docker-engine
#apt-get update
#apt-get upgrade -y
#apt-get install -y linux-image-extra-"$(uname -r)"
#apt-get install -y docker-engine
#service docker start
#apt-get install -y vim