#!/bin/bash

apt-get upgrade
apt-get update

#wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
#deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main
#apt-get update
sudo apt-get install salt-minion -y
sudo apt-get install salt-ssh -y
sudo apt-get install salt-syndic -y
sudo apt-get install salt-cloud -y
sudo apt-get install salt-api -y
sudo systemctl restart salt-minion
echo "master: 10.10.9.85" >> /etc/salt/minion
sudo systemctl restart salt-minion

sed -i "1 a127.0.1.1 $HOSTNAME" /etc/hosts


#syslog
apt-get install syslog-ng -y
sed -i "s\#destination d_net { tcp(\"127.0.0.1\" port(1000) log_fifo_size(1000)); };\destination d_net { tcp(\"10.10.9.85\" port(51234) log_fifo_size(1000)); };\ " /etc/syslog-ng/syslog-ng.conf

sed -i "s\#log { source(s_src); destination(d_net); };\log { source(s_src); destination(d_net); };\ " /etc/syslog-ng/syslog-ng.conf

service syslog-ng stop
service syslog-ng start