#!/bin/bash
#apache2
apt-get install apache2 -y
echo "ServerName $(hostname -I)" >> /etc/apache2/apache2.conf
systemctl restart apache2

#php
apt-get install php libapache2-mod-php php-mcrypt php-mysql -y
sed -i "s\\s*DirectoryIndex.*\    DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm\ " /etc/apache2/mods-enabled/dir.conf
systemctl restart apache2

#nagios
useradd nagios
groupadd nagcmd
usermod -a -G nagcmd nagios
apt-get update
apt-get install build-essential libgd2-xpm-dev openssl libssl-dev unzip -y
curl -L -O https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.3.4.tar.gz
tar zxf nagios-*.tar.gz
cd nagios-*
./configure --with-nagios-group=nagios --with-command-group=nagcmd
make all
make install
make install-commandmode
make install-init
make install-config
/usr/bin/install -c -m 644 sample-config/httpd.conf /etc/apache2/sites-available/nagios.conf
usermod -G nagcmd www-data

#nrpe plugin
#curl -L -O https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
#tar zxf nrpe-*.tar.gz
#cd nrpe-*
#./configure
#make check_nrpe
#make install-plugin
#sed -i "s\#cfg_dir=/usr/local/nagios/etc/servers\cfg_dir=/usr/local/nagios/etc/servers\ " /usr/local/nagios/etc/nagios.cfg


a2enmod rewrite
a2enmod cgi
service apache2 restart
htpasswd -b -c /usr/local/nagios/etc/htpasswd.users nagiosadmin root
ln -s /etc/apache2/sites-available/nagios.conf /etc/apache2/sites-enabled/
systemctl restart apache2

echo '[Unit]
Description=Nagios
BindTo=network.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=nagios
Group=nagios
ExecStart=/usr/local/nagios/bin/nagios /usr/local/nagios/etc/nagios.cfg' >> /etc/systemd/system/nagios.service


#nagiosadmin

# <------ NRPE ----->
curl -L -O https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
tar zxf nrpe-*.tar.gz
cd nrpe-*
./configure
make check_nrpe
sudo make install-plugin

sed -i "s\#cfg_dir=/usr/local/nagios/etc/servers\cfg_dir=/usr/local/nagios/etc/servers \ " /usr/local/nagios/etc/nagios.cfg

mkdir /usr/local/nagios/etc/servers


echo "define command{
        command_name check_nrpe
        command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
}" >> /usr/local/nagios/etc/objects/commands.cfg


systemctl restart apache2
systemctl enable /etc/systemd/system/nagios.service
systemctl start nagios