#!/bin/bash

#syslog
apt-get install syslog-ng -y

ipaddress=$(hostname -I)

#etc/syslog-ng/syslog-ng.conf

sed -i "s\#source s_net { tcp(ip(127.0.0.1) port(1000)); };\source s_net { tcp(ip($(hostname -I)) port(51234)); };\ " /etc/syslog-ng/syslog-ng.conf
sed -i -e "/source s_sr.*/,+3d" /etc/syslog-ng/syslog-ng.conf

service syslog-ng start